<!-- This is generated by the vue create command                         -->
<!-- We will be adding things to this file related to our Vue components -->
<template> <!-- html for the Vue component -->
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <!-- A Vue component is a custom html tag created by programmers, they're not standard html tags -->
    <product-review></product-review> <!-- use our new Vue component - NOTE: name is kabob-case -->
  </div>
</template>

<script>   // JavaScript for the Vue component
// The src folder in the Vue project is considered the root folder for the project
// References to any other files/folders in the project are relative to the src folder
import ProductReview from './components/ProductReview.vue' // Go get the ProductReview.vue code

// export allow processes (like Vue) access to data defined in this JavaScript code
// default is the default name for an object shared outside of the code
export default { // export exposes data to things outside this component (like Vue)
  name: 'App',   // name of the application - matches the name of the component
  components: {  // list of all the Vue components used in this file
    ProductReview   // tells Vue we are using the ProductReview component - must match import name
  }
}
</script>

<style>    /* CSS for the Vue component */
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
